### ISSUE TITLE
Homepage review

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#11]
@oxySmith @li-btu I've implemented the homepage, can you give me a review
pull the latest changes on the develop branch

**Comment by oxySmith** [comment]
@lakeside213  Looks nice, you may change justify-content to center in  .grid-section css class to make product items aligned by center while resizing

**Comment by lekankoku** [comment]
![image](https://user-images.githubusercontent.com/19761486/146759629-ab36f39b-6ded-4a41-8aae-f5280d93e5f9.png)

mobile view
![image](https://user-images.githubusercontent.com/19761486/146759773-c0d9d4bb-5b15-4631-ba46-fd98d234aadc.png)

@oxySmith i've been able to center the content

**Comment by oxySmith** [comment]
@lakeside213 Looks great
