### ISSUE TITLE
Product Detail Review 

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#12]
@oxySmith @li-btu can you review the product detail page and give me feedback

**Comment by li-btu** [comment]
@lakeside213 The product detail page's layout looks great. But could you please change all the Dollar signs to Euro signs? Other than that I think everything is fine. Thanks.

**Comment by li-btu** [comment]
Sorry, there is another issue. The pages' title should be changed to the product name.

**Comment by lekankoku** [comment]
@li-btu i've fixed the issue. can you review

**Comment by li-btu** [comment]
Verified fixed.
