### ISSUE TITLE
Products page

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#13]
@oxySmith @li-btu can you review the products page and give me feedback

**Comment by li-btu** [comment]
@lakeside213 There are a few issues:
1. Please change the title of the page according to our requirement
2. Add hyperlinks to the product images which have a product page
3. Change dollar signs to euro signs
4. Add units to the product prices
5. Disable hyperlinks of products which do not have their product page

**Comment by lekankoku** [comment]
@li-btu can you review, i've deployed a few fixes

**Comment by li-btu** [comment]
Looks good.
