### ISSUE TITLE
Recipes Page Review

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#17]
@oxySmith @li-btu can you review the recipes page and give me feedback

**Comment by li-btu** [comment]
@lakeside213 It looks great. But you're missing a "banner" for "View marvellous recipes in these videos".
![image](https://user-images.githubusercontent.com/94308833/147957114-e8e2faa0-be5b-4815-b41d-93d715cf5d12.png)

**Comment by lekankoku** [comment]
@li-btu I've added the banner, can you review again

**Comment by oxySmith** [comment]
@lakeside213 it seems that recipies page is unavailable from the header

**Comment by lekankoku** [comment]
that was a typo, i've fixed it now

**Comment by oxySmith** [comment]
@lakeside213 seems nice from my side

**Comment by li-btu** [comment]
Agree. It looks good now
