### ISSUE TITLE
About Page Review

### ISSUE THREAD

**Issue by Billy007p** [oxySmith/webdocs-assignment2#18]

**Comment by Billy007p** [comment]
@li-btu @oxySmith can you review the About page and give me feedback

**Comment by li-btu** [comment]
The slideshow's size is bigger than the browser. Can you please make it smaller? It doesn't have to be full screen for such low resolution images.
Also, the body text section is too wide, which makes it hard to focus. Could you please make the whole division narrower?

**Comment by Billy007p** [comment]
done , could you check that please and tell me then if its okay now ?
plus i need to know which images you want us to include in the slideshow.

**Comment by oxySmith** [comment]
@Billy007p feel free to use any pictures, there is no preference from our side. Looks good for me.
