### ISSUE TITLE
Missing SVG Logo

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#2]
@oxySmith @li-btu can you upload the SVG format of your logo.

**Comment by oxySmith** [comment]
@lakeside213 @Billy007p Sorry, but we do not have an svg icon, we have only png and jpeg. Please use them.

**Comment by lekankoku** [comment]
Okay, everything is fine now, as  you have uploaded the transparent png.
I'll close the issue
