### ISSUE TITLE
terms page 

### ISSUE THREAD

**Issue by Billy007p** [oxySmith/webdocs-assignment2#20]
where can i get the terms and conditions which you wrote ? @oxySmith @li-btu

**Comment by oxySmith** [comment]
@Billy007p  terms and conditions text is in the webpages-list.html
https://github.com/oxySmith/webdocs-assignment2/blob/main/assignment-2a/website-content/webpages-list.html

**Comment by Billy007p** [comment]
@oxySmith @li-btu  could you please have a look on the page ?

**Comment by li-btu** [comment]
@Billy007p It looks fine to me

**Comment by oxySmith** [comment]
@Billy007p for me as well
