### ISSUE TITLE
Write us

### ISSUE THREAD

**Issue by Billy007p** [oxySmith/webdocs-assignment2#21]
@oxySmith  @li-btu  Could you please the write us page and give me some feedback , thanks.

**Comment by li-btu** [comment]
@Billy007p There are a few things that can be improved.
1. The breadcrumb "Contact > Write us" is missing
2. The email, name and subject fields should be much longer
3. The pre-filled white spaces in the content text area should be removed.

![image](https://user-images.githubusercontent.com/94308833/148694986-791c9bcc-6f8e-4e43-b7c6-6a800ee3ee83.png)

**Comment by li-btu** [comment]
I've checked that you've added the breadcrumb and lengthened the text fields. The white spaces in the text area remain but it would not affect the usability, thus it's acceptable.
