### ISSUE TITLE
Missing icon library

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#4]
@oxySmith @li-btu There are no SVG files for the icons you provided in the wireframe

for example the thunderbolt here is missing
![image](https://user-images.githubusercontent.com/19761486/145708547-59c5318c-1564-47d5-bd88-b90415f54160.png)

Can you supply the icons or are we free to source them as we choose?

**Comment by li-btu** [comment]
Sorry, we don't have them either. They're from Balsamiq. Please feel free to find similar icons online.

**Comment by lekankoku** [comment]
Okay no problem, we would use SVG icons from https://fontawesome.com/ .

**Comment by oxySmith** [comment]
yes, you can download css and font files from zip archive located in download section https://fontawesome.com/v4.7/get-started/

**Comment by oxySmith** [comment]
example of usage:
https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-bolt
