### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#5]
The header is a component that is used on all pages, hence we decided to componentize it via HTML Web Components
Acceptance Criteria
- The header should scale according to web view
- The Mobile side should be function via javascript

Wireframe
![image](https://user-images.githubusercontent.com/19761486/146637915-579845ed-6ef5-4c22-8975-79f38bf52693.png)

**Comment by lekankoku** [comment]
![image](https://user-images.githubusercontent.com/19761486/146640369-9337156a-7cfb-4ed5-97e9-1f7ab0b6a2b5.png)
@oxySmith @li-btu there was no color specified for the nav links, am I allowed to choose the color or if not what color code is this(the home text) ?

**Comment by lekankoku** [comment]
@oxySmith @li-btu is it also necessary to have the black separators separating the links?

**Comment by li-btu** [comment]
@lakeside213 You may use white color for the nav links, and a light yellow color of your choice when hovered. The separators are not necessary.

Our base color is orange(#F38D3F) and accent color is light yellow. Other than these colors you can use white and shades of grey.

**Comment by lekankoku** [comment]
@li-btu @oxySmith  i've been able to implement a prototype of the header, can you pull the current develop branch and check it out on the index.html page and give me a review.

NB:check out the mobile view as well

**Comment by li-btu** [comment]
@lakeside213 It would be better if you could keep a minimum distance between each word when the browser size is squeezed.
![image](https://user-images.githubusercontent.com/94308833/146642532-abd10c67-e8c3-48bf-8bfa-7eee5a3bfbde.png)

**Comment by lekankoku** [comment]
@li-btu i've fixed that by using a media query which starts from that screen width, pull the latest changes

> @lakeside213 It would be better if you could keep a minimum distance between each word when the browser size is squeezed. ![image](https://user-images.githubusercontent.com/94308833/146642532-abd10c67-e8c3-48bf-8bfa-7eee5a3bfbde.png)

**Comment by lekankoku** [comment]
In closing are you @li-btu @oxySmith satisfied with the header ?

**Comment by li-btu** [comment]
@lakeside213 It looks nice. There are only some minor things to improve.
1. The texts on the navigation bar in the mobile version currently do not change color when hovered. Please change its color to light yellow when hovered and underline the page the user is currently on.
2. When the brand name or logo is clicked, it should redirect to the home page.

**Comment by lekankoku** [comment]
1.  There are no hover events for mobile(you literally can only click and long press on mobiles)

**Comment by li-btu** [comment]
Regarding #1, sorry, I mean the desktop version when the browser is small enough

**Comment by lekankoku** [comment]
i've fixed the issues can you check the develop branch again @li-btu

**Comment by li-btu** [comment]
Looks good now. Thanks
