### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#6]
The Footer is a component that is used on all pages, hence we decided to componentize it via HTML Web Components
Acceptance Criteria

The footer should scale according to web view
![image](https://user-images.githubusercontent.com/19761486/146637986-71946945-f86e-4ffa-81cd-29b42202f418.png)

**Comment by lekankoku** [comment]
@oxySmith @li-btu I've implemented the footer, can you review it

**Comment by oxySmith** [comment]
@lakeside213 seems nice to me, you may fix typo in word 'Conditions' and separate the links 'Terms and conditions' and 'Credits'
![image](https://user-images.githubusercontent.com/28259725/146755125-0265d1c5-6987-4d57-98ca-dd067a2aa2bd.png)

**Comment by lekankoku** [comment]
> 

@oxySmith i've fixed the typo and i've also hyperlinked the credits page as well

**Comment by lekankoku** [comment]
In closing are you @li-btu @oxySmith satisfied with the footer ?

**Comment by oxySmith** [comment]
@lakeside213 yes, footer is nice
