### ISSUE TITLE
Item Card Component

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#7]
The item is used on multiple with some dynamic features such as discounts on certain pages

Acceptance criteria
1. The discount icon should be dynamic
2. Component must scale well across display sizes
![image](https://user-images.githubusercontent.com/19761486/146638018-e0d30e60-3b4b-45d4-97ca-d3ae966c40ce.png)

**Comment by lekankoku** [comment]
In closing are you @li-btu @oxySmith satisfied with the product cards(+discount card)?

**Comment by li-btu** [comment]
@lakeside213 You do not need to implement hyperlink for the products which do not have its own product detail page. And like my comments for the product page, the product price and units of the products should be aligned with our requirements. Other than that, the page looks good!

**Comment by li-btu** [comment]
Page title should also be changed

**Comment by lekankoku** [comment]
@li-btu I've fixed the pending issues, can you review them

**Comment by li-btu** [comment]
Everything's fine.
