### ISSUE TITLE
Slideshow Component 

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#9]
![image](https://user-images.githubusercontent.com/19761486/146643761-3cba30bb-1d0b-4281-8a3f-724d538e7cee.png)

**Comment by Billy007p** [comment]
@oxySmith @li-btu which images should we add to the slideshow, can we select randomly or do you have preferences

**Comment by oxySmith** [comment]
@lakeside213 we do not have any prefence
